### ISSUE TITLE
Browse of cyclically linked cells causes crash

### ISSUE THREAD

**Issue by petervanroy** [mozart/mozart2#167]
Feeding this causes crash of browser and Mozart process:

declare
L1={NewCell pack(L1)}
{Browse @L1}

**Comment by Jimvy** [comment]
The issue is still there. It doesn't happen with {Show @L1}. The following code also causes the same kind of crash, only when we try to use the Browser:
```
declare
C={NewCell truc({NewCell C})}
{Browse @C}
```

**Comment by layus** [comment]
@petervanroy What is it supposed to print ?

**Comment by petervanroy** [comment]
Browse is not supposed to look inside cells.

Peter
