### ISSUE TITLE
Support of the UTF-8 "BOM"

### ISSUE THREAD

**Issue by layus** [mozart/mozart2#253]
It seems to me that mozart2 fails to compile a file starting with the utf-8 "BOM".
This BOM is not common everywhere, but widely used on windows.

Here are the tests I made on my linux machine 

```
layus@ankh-morpork$ hexdump -C test.oz
00000000  ef bb bf 66 75 6e 63 74  6f 72 20 65 6e 64 0a     |...functor end.|
0000000f
layus@ankh-morpork$ ozc -c test.oz    
Mozart Compiler 2.0.0-alpha.0+build.4138.3739933-dirty (Tue, 28 Oct 2014 18:24:57 +0800) playing Oz 3

%%% feeding file test.oz

%*************************** parse error ************************
%**
%** parse error
%**
%** in file "test.oz", line 1, column 2
%** ------------------ rejected (1 error)
```

Is there an easy way to support it, or to make the reported error more verbose ?

**Comment by sjrd** [comment]
UTF-8 BOM is a sin. Don't support it.
I suppose the error message could be made clearer. @eregon would be the one to ask.

**Comment by layus** [comment]
:-)

**Comment by eregon** [comment]
@sjrd Why me?
I agree though, BOM is mainly considered deprecated these days.

**Comment by sjrd** [comment]
Er, for some reason I associated you with the parser. But it's the pickler you worked on, indeed.

So, to anyone interested, the entry point of the parser is here: https://github.com/mozart/mozart2/blob/master/lib/compiler/Parser.oz#L440-L454

**Comment by layus** [comment]
Noone is really interested in this issue... UTF-8 BOM should disappear from Windows... Closing :-)
