### ISSUE TITLE
mozart-oz.org repository URL is misleading

### ISSUE THREAD

**Issue by almereyda** [mozart/mozart2#260]
[As of a comment](https://github.com/mozart/mozart2/issues/33#issuecomment-22841569) by @nruth almost two years ago, the official project website is to be [mozart.github.io](http://mozart.github.io/).

Yet the current repository URL leads to [mozart-oz.org](http://www.mozart-oz.org/) which has been overtaken by domain squatters.

It would already help to just switch these URLs in the settings here.

**Comment by petervanroy** [comment]
On 23/3/2015 18:49, Jon Richter wrote:
>
> As of a comment 
> <https://github.com/mozart/mozart2/issues/33#issuecomment-22841569> by 
> @nruth <https://github.com/nruth> almost two years ago, the official 
> project website is to be mozart.github.io <http://mozart.github.io/>.
>
> Yet the current repository URL leads to mozart-oz.org 
> <http://www.mozart-oz.org/> which has been overtaken by domain squatters.
>
> It would already help to just switch these URLs in the settings here.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mozart/mozart2/issues/260>.
>
I'm trying to get it back, but probably won't succeed (I don't want to 
pay a fortune to those parasites).  We will pick another domain name.  
For now, you should use http://mozart.github.io/.

Peter

**Comment by allentiak** [comment]
@almereyda
From what I can see, the URI has been corrected in the repository settings. Should this bug be closed?
