### ISSUE TITLE
vm CMakeLists.txt

### ISSUE THREAD

**Issue by kainwen** [mozart/mozart2#262]
https://github.com/mozart/mozart2/blob/master/vm/CMakeLists.txt#L8

When I compile mozart2, cmake throw errors. And I found the reason is  LLVM_BUILD_DIR and LLVM_SRC_DIR is not corret. 

After I hard code the PATH,  the compilation is OK.

**Comment by layus** [comment]
That's the reason why LLVM_BUILD_DIR and LLVM_SRC_DIR are configurable with the -D option of cmake ?
If you do not download LLVM sources in the recommended location ${CMAKE_BINARY_DIR}/externals/Source/llvm" then you need to provide these variables using -D.

See 
https://github.com/mozart/mozart2#suggested-directory-layout
https://github.com/mozart/mozart2#obtaining-gtest-and-llvm
https://github.com/mozart/mozart2#build-mozart

**Comment by kainwen** [comment]
At first I use the cmake -D option. But it does not work.
And the result is same as the issue here:     https://github.com/mozart/mozart2/issues/258

**Comment by layus** [comment]
Changing the line https://github.com/mozart/mozart2/blob/master/vm/CMakeLists.txt#L8 in the source code is useless. 

If you did 
```diff
-set(DEFAULT_LLVM_SRC_DIR "${ep_base}/Source/llvm")
+set(DEFAULT_LLVM_SRC_DIR "/my/hard/coded/path/")
```

Then calling `$ cmake -DLLVM_SRC_DIR=/my/hard/coded/path/` would have exactly the same effect.
