### ISSUE TITLE
mac os x el captain mozart 2 java problem

### ISSUE THREAD

**Issue by israelcvidal** [mozart/mozart2#263]
I'm having a problem with Java. I used the command "brew install --HEAD mozart2" and got this message:
"mozart2: Java 1.6 is required to install this formula.", but I already have java. I also tried reinstalling it but it didn't work. I think maybe the problem is that I have a newer Java version(1.8) and maybe there's a bug that only accepts the 1.6 version.
Could anybody help me? (:

**Comment by eregon** [comment]
Does the released version work for you? It would be much simpler:
http://sourceforge.net/projects/mozart-oz/files/v2.0.0-alpha.0/

**Comment by israelcvidal** [comment]
It worked, eregon! Thanks! (: I should have tried it first!
