### ISSUE TITLE
Needs more tooling documentation

### ISSUE THREAD

**Issue by MadcapJake** [mozart/mozart2#264]
I'm taking the Louv1.1x course on edx and I am really enjoying Mozart/Oz! However I am terrible at emacs :disappointed:.

So, I have been working on adding support into [Atom](https://atom.io/).  Actually there already is a [language-oz](https://github.com/kennytm/language-oz) package available but unfortunately it doesn't really work very well (It's mostly just a conversion of a not-so-good tmBundle).

As I've been learning Oz, I've been tuning and tweaking the package to not only highlight as per the emacs highlighter but also to go a step further (Atom's highlighting support is actually really extensive). On top of just highlighting `oz` files, atom packages can also provide hooks to other packages and there is an autocomplete hook and a build hook that would make writing and running oz files as simple as downloading two packages (autocomplete is builtin so you'd just need [atom-build](https://github.com/noseglid/atom-build) and language-mozart).  But there could be so much more! A full translation of the Mozart opi to Atom would be ideal.

My issue is that I would really like to bring some of the awesome opi functionality to Atom but I could use some help understanding how to dig into the opi files (especially the emacslisp part).

Here's some basic tooling I've rigged up:

#### ozv executable script
```shell
#!/bin/zsh
ozfile=$1;
ozc -c "$ozfile.oz"
ozengine "$ozfile.ozf"
if [ $? -eq 0 ]; then
  exit 0
else
  exit 1
fi
```
The error code check at the end is because atom-build will allow me to regex match against error messages and move the cursor to the line in question as long as the spawned process ends with a fail code.

#### atom-build custom build json file
```json
{
    "OZ: compile and run": {
      "cmd": "./ozv",
      "args": ["{FILE_ACTIVE_NAME_BASE}"],
      "errorMatch": "\\%\\*{2} in file \\\"(?<file>.*\\.oz)\\\", line (?<line>\\d+), column (?<col>\\d+)",
      "keymap": "alt-z a"
    }
}
```
It works! I have to use `System.show` instead of the shortcuts that the opi provides. Unfortunately, `Browser.browse` doesn't seem to work (though there are a bunch of `oz*` processes running in the background).

Anyways, if anyone has any kind of help it'd be greatly appreciated.  I am especially interested in learning more about:
* Command line tool usage
* Using Browser
* Using Inspector
* Understanding and translating the emacslisp of the opi

I'd also like to add that I really want to make sure that I am focusing on finishing the coursework as I am still very new to Oz syntax/semantics, so I won't go full bore into this until after that.  However, I do plan on uploading `language-mozart`, a more extensive highlighter for Atom, over the weekend sometime.

**Comment by xhevahir** [comment]
A year ago there was some discussion of this [in the mozart-users newsgroup](https://groups.google.com/forum/#!searchin/mozart-users/repl/mozart-users/6aFrt6KK8RE/G5EHDTJG5nUJ) . The link to the 'mosh' shell that someone mentioned is dead; the description of it is [here](https://www.sics.se/~nilsf/mogul/doc/mathweb-mosh/mathweb-mosh.html) .

**Comment by layus** [comment]
Nice job !

You would find a good example of such tooling with the Gedit plugin at https://github.com/mmxgn/mozart-stuff/tree/master/mozart-gedit/

To mimic emacs OPI, you need to start a mozart server and feed chunks to it. A simpler solution is to spawn a short-lived instance for each chunk you want to evaluate.

**Comment by layus** [comment]
closing as not-really-an-issue. Feel free to reopen/continue to comment.
