### ISSUE TITLE
Mozart2 doesn't compile [OpenBSD 5.9 (amd64) ]

### ISSUE THREAD

**Issue by AminaRepo** [mozart/mozart2#277]
Hi,
I tried to compile mozart2 following the instructions in both README.md and OpenBSD.md.
After the last 'make' command (the compile of llvm and gtest have been done), I've got this:
[  0%] Linking CXX executable generator
/.../.../mozcode/builds/llvm-release/lib/libclang.so.3.8: warning: warning: sprintf() is often misused, please use snprintf()
CMakeFiles/generator.dir/generator.cc.o: In function `baseIsNotModule(clang::CXXRecordDecl const*, void*)':
generator.cc:(.text+0x50): undefined reference to `clang::DeclarationName::getAsString() const'
........
utils.cc:(.text+0x21a): undefined reference to `clang::QualType::getAsString(clang::PrintingPolicy const&) const'
.........

utils.cc:(.text+0x468b): undefined reference to `llvm::raw_ostream::write(char const*, unsigned long)'
collect2: error: ld returned 1 exit status
*** Error 1 in . (vm/generator/main/CMakeFiles/generator.dir/build.make:200 'vm/generator/main/generator')
*** Error 1 in . (CMakeFiles/Makefile2:128 'vm/generator/main/CMakeFiles/generator.dir/all')
*** Error 1 in /.../.../mozcode/builds/mozart2-release (Makefile:161 'all')

-----------------------------------

System: OpenBSD 5.9 (amd64)
gcc version : updated to 4.9.3
llvm(clang) release : 3.8.0 (same issue with 3.8.1 )
boost version: 1.58
tcl version: 8.6
tk version: 8.6

**Comment by layus** [comment]
Hi,
You may find inspiration in the [ArchLinux PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mozart2-git)

I had to patch the build procedure to link against clang libs. Most linux distros provide only a skinny libclang.so, and symbols are missing in there. The current cmake build does not handle this.

The interesting part is 
```bash
prepare() {
    [...]
    libs="LLVM clang clangTooling clangFrontendTool clangFrontend \
          clangDriver clangSerialization clangCodeGen clangParse clangSema \
          clangStaticAnalyzerFrontend clangStaticAnalyzerCheckers \
          clangStaticAnalyzerCore clangAnalysis clangARCMigrate clangEdit \
          clangAST clangLex clangBasic"
    sed -i'' \
        -e "s%(generator \"\${CLANG_LIBRARY}\"%\\0 $libs%" \
        vm/generator/main/CMakeLists.txt
    [...]
}
```

**Comment by layus** [comment]
Closing for now, feel free to reopen if you need more info.
