### ISSUE TITLE
Is ozcar (debugger) present on mozart2?

### ISSUE THREAD

**Issue by hanoii** [mozart/mozart2#288]
I can't seem to get it to run on OSX.

I get:

```
%********************** Error: module manager *******************
%**
%** Could not link module
%**
%** Could not load functor at URL: x-oz://system/Ozcar.ozf
%**--------------------------------------------------------------
```

Is there a way to run it?

**Comment by layus** [comment]
AFAIK, it was never supported/implemented in mozart2. Mozart1.4 is probably your best bet if you really need the debugger.

**Comment by layus** [comment]
Mozart2 is lacking resources, and will not receive little attention outside of bugfixes in the forseable future. Closing as it is definitely something we should do and already present in our internal wishlist.

**Comment by sjmackenzie** [comment]
@hanoii we'll definitely accept patches, so if you're willing, crack those knuckles and get oscar up and running on mozart2!
