### ISSUE TITLE
Declare statement not working in ozc

### ISSUE THREAD

**Issue by rharish101** [mozart/mozart2#324]
Declare statements do not work when I try to compile using `ozc -c`.

Example code:
```
functor
   import System
define

declare X in
X = 1
{System.show X}

end
```

The error thrown is:
```
Mozart Compiler 2.0.1 (Wed, 5 Sep 2018 03:16:51 +0200) playing Oz 3

%%% feeding file test.oz

%*************************** parse error ************************
%**
%** expected '!'
%**
%** (other candidates: character, integer, atom, variable, float, string, '_', '$', 'self', 'fail' or one of 23 others)
%** in file "test.oz", line 5, column 1
%** file "test.oz", line 1, column 1: inside functor definition
%** ------------------ rejected (1 error)
```

What should happen: I expect this to run and output 1.

My system:
* Arch Linux with x86-64 architecture
* Mozart2 v2.0.1

**Comment by layus** [comment]
Inside a functor declare does not work. Use local ... in ... end or rely on the define that you already have and works much like a declare.

More generally, avoid define as much as possible, it has a very strange semantics.

G.

Le 25 septembre 2019 19:36:27 UTC+02:00, Harish Rajagopal <notifications@github.com> a écrit :

Declare statements do not work when I try to compile using ozc -c.

Example code:

functor
   import System
define

declare X in
X = 1
{System.show X}

end


The error thrown is:

Mozart Compiler 2.0.1 (Wed, 5 Sep 2018 03:16:51 +0200) playing Oz 3

%%% feeding file test.oz

%*************************** parse error ************************
%**
%** expected '!'
%**
%** (other candidates: character, integer, atom, variable, float, string, '_', '$', 'self', 'fail' or one of 23 others)
%** in file "test.oz", line 5, column 1
%** file "test.oz", line 1, column 1: inside functor definition
%** ------------------ rejected (1 error)


My system:

  *   Arch Linux with x86-64 architecture
  *   Mozart2 v2.0.1

**Comment by eregon** [comment]
> More generally, avoid __*declare*__ as much as possible, it has a very strange semantics.

Indeed, this is intentional.
