### ISSUE TITLE
ozc if statement troubles

### ISSUE THREAD

**Issue by Prasantacharya** [mozart/mozart2#337]
So, I am learning oz and was trying to run an oz program from the terminal using ozc and ozengine. The code is fairly basic, basically a naive implementation of Fibonacci:
```
functor
import
    System
    Application
define

fun {Fib N}
    if (N <= 1) then 1 else {Fib (N-1)} + {Fib (N-2)} end
end

{System.showInfo {Fib 7}}
{Application.exit 0}
end
```
However, when i try and compile with ozc, i get
```
$ ozc -c fib.oz   
Mozart Compiler 2.0.1 (Wed, 5 Sep 2018 03:16:51 +0200) playing Oz 3

%%% feeding file fib.oz

%*************************** parse error ************************
%**
%** expected 'then'
%**
%** (other candidates: '^', '.', ',', 'div', 'mod', '/', '*', '-', '+', '|' or one of 53 others)
%** in file "fib.oz", line 8, column 10
%** file "fib.oz", line 8, column 5: inside if phrase
%** file "fib.oz", line 7, column 1: inside function definition
%** file "fib.oz", line 1, column 1: inside functor definition
%** ------------------ rejected (1 error)
```
This is odd to me, because I dont think i have the syntax wrong for the if statement. If i am doing something wrong here, please let me know, I am still learning. However this looks to me that it may be a problem with ozc?

**Comment by Prasantacharya** [comment]
Never mind, I was just being very dumb. i should have used =<, it compiles and runs with that.

**Comment by layus** [comment]
I am glad that you found the solution by yourself. And you are certainly not stupid. Oz comes with quirks like that one. As a memo, you can remember that inequalities never take the form of an arrow, as arrows are used elsewhere. So it's =< and >= and not <= and =>. This has been a source of countless mistakes as it is not very consistent and different from most languages out there.

Le 30 septembre 2021 05:16:15 GMT+02:00, Prasant Acharya ***@***.***> a écrit :
