### ISSUE TITLE
Pickle not working properly

### ISSUE THREAD

**Issue by jaymelbe** [mozart/mozart2#91]
Hello, I am trying to use Pickle to exchange data between 2 processes through a file but there seems to be something wrong.

I am trying to do this:
{Pickle.save 1 'bar'}
{Browse {Pickle.load 'bar'}}

But even this small example does not work. Am I doing something wrong? It creates a file (looking good so far) but it cannot read the file with the Pickle.load function.
The error message is:
%*************************** type error *************************
%**
%** Expected type: file
%** At argument:   1
%** In statement:  {unit <Object>}
%**
%** Call Stack:
%** procedure 'OS.fread' in PC = 18198384
%** procedure 'Read' in file "/home/jmelchior/projects/mozart2/lib/main/sys/Pickle.oz", line 556, column 7, PC = 140591195715579
%** procedure 'ReadInt' in file "/home/jmelchior/projects/mozart2/lib/main/sys/Pickle.oz", line 566, column 7, PC = 140591195714832
%** procedure 'ReadValueFromSource' in file "/home/jmelchior/projects/mozart2/lib/main/sys/Pickle.oz", line 555, column 4, PC = 140591195738768
%** procedure 'LoadWithHeader' in file "/home/jmelchior/projects/mozart2/lib/main/sys/Pickle.oz", line 204, column 4, PC = 140591195743814
%** procedure 'Load' in file "/home/jmelchior/projects/mozart2/lib/main/sys/Pickle.oz", line 200, column 4, PC = 140591195744066
%** toplevel abstraction in line 1, column 0, PC = 140591211379074
%**--------------------------------------------------------------

**Comment by layus** [comment]
Seems to be working correctly thanks to the work on VM's.
